### ISSUE TITLE
Unable to alternate song location

### ISSUE THREAD

**Issue by throwaway9098** [MyLegGuy/GrowtopiaMusicSimulatorFinal#2]
I've turned storage permission on, cleared cache/data, reinstalled.
There are no GMSF files, and the app doesn't recognize that it has the permission.
How do I fix this?

**Comment by MyLegGuy** [comment]
Try creating a folder called "GMSF" and then see if it lets you enable the alternate location.

**Comment by throwaway9098** [comment]
That surprisingly worked, thank you so much for the help.
