### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by cwkhawand** [MyLegGuy/GrowtopiaMusicSimulatorFinal#3]
Is this software abandoned?

**Comment by MyLegGuy** [comment]
i don't play the game anymore, so if there are new things in growtopia then i'm not aware of them.
if there are new notes in growtopia, i can add them easily.
if there are new features in growtopia, i'll consider adding them.

if this program has bugs, i will probably fix them. (but there was this guy who told me the program didn't launch on some ancient windows 32 bit and i ignored him.)
i'm not really interested in updating the mobile version UI.

**Comment by yEsPaP** [comment]
> i don't play the game anymore, so if there are new things in growtopia then i'm not aware of them.
> if there are new notes in growtopia, i can add them easily.
> if there are new features in growtopia, i'll consider adding them.
> 
> if this program has bugs, i will probably fix them. (but there was this guy who told me the program didn't launch on some ancient windows 32 bit and i ignored him.)
> i'm not really interested in updating the mobile version UI.

its fine but why consuming 25% cpu

**Comment by TheCoolDoge** [comment]
> i don't play the game anymore, so if there are new things in growtopia then i'm not aware of them. if there are new notes in growtopia, i can add them easily. if there are new features in growtopia, i'll consider adding them.
> 
> if this program has bugs, i will probably fix them. (but there was this guy who told me the program didn't launch on some ancient windows 32 bit and i ignored him.) i'm not really interested in updating the mobile version UI.

If you're any interested in the subject, new notes have been added to the game within the past few updates, an example being the mexican trumpet. Many music makers would really appreciate if you were to update the planner; thanks for having made it regardless.

**Comment by cwkhawand** [comment]
> > i don't play the game anymore, so if there are new things in growtopia then i'm not aware of them. if there are new notes in growtopia, i can add them easily. if there are new features in growtopia, i'll consider adding them.
> > if this program has bugs, i will probably fix them. (but there was this guy who told me the program didn't launch on some ancient windows 32 bit and i ignored him.) i'm not really interested in updating the mobile version UI.
> 
> If you're any interested in the subject, new notes have been added to the game within the past few updates, an example being the mexican trumpet. Many music makers would really appreciate if you were to update the planner; thanks for having made it in the first place.

There's a new web-based music simulator that has all new notes as well as an intuitive user interface:
https://music-simulator.growtopia.tech

**Comment by TheCoolDoge** [comment]
> > > i don't play the game anymore, so if there are new things in growtopia then i'm not aware of them. if there are new notes in growtopia, i can add them easily. if there are new features in growtopia, i'll consider adding them.
> > > if this program has bugs, i will probably fix them. (but there was this guy who told me the program didn't launch on some ancient windows 32 bit and i ignored him.) i'm not really interested in updating the mobile version UI.
> > 
> > 
> > If you're any interested in the subject, new notes have been added to the game within the past few updates, an example being the mexican trumpet. Many music makers would really appreciate if you were to update the planner; thanks for having made it in the first place.
> 
> There's a new web-based music simulator that has all new notes as well as an intuitive user interface: https://music-simulator.growtopia.tech

Thanks for letting me know, I'm definitely going to use this. It's kind of sad how you can't go any further than the normal world size like it's possible in your planner though.

**Comment by MyLegGuy** [comment]
the only note that's missing is the mexican trumpet. it has lyre and electric guitar and all the other horrible ones.

I don't have time at this exact moment to make an updated android version, so I hope you're on windows.
here is a version with the trumpet:
[new-version.zip](https://github.com/MyLegGuy/GrowtopiaMusicSimulatorFinal/files/7665348/new-version.zip)

> There's a new web-based music simulator that has all new notes as well as an intuitive user interface: https://music-simulator.growtopia.tech

I like hearing about these. I am always amused by their pathetic attempts to replicate my extremely simple program.
Perhaps you could make a weak argument that the UI is intuitive, but it's definitely not good. Not even close.
These script kiddies are too busy focusing on their security-through-obscurity to make a functioning program.
