### ISSUE TITLE
New notes

### ISSUE THREAD

**Issue by 1234r5** [MyLegGuy/GrowtopiaMusicSimulatorFinal#4]
Since i know you've quit the game i'm only posting this to let you know that they've added some new notes to the game today. Would it be possible for you to add them to the simulator or are you done with it as well? Don't wanna put this on you if you feel you are done with everything related to Growtopia.

**Comment by MyLegGuy** [comment]
thank you for the notice.
the pc version is out and the google play version will be updated whenever google approves it.
